const svg = document.querySelector('#graph'); let active='all', selected=null, graphData={};
const typeFor = n => n.kind || (n.related_skill_id !== undefined ? 'task' : n.confidence !== undefined ? 'skill' : n.priority !== undefined ? 'goal' : 'agent');
const color={skill:'#66d9a3',task:'#ffd166',goal:'#85b8ff',agent:'#ed8cff'};
function nodeData(data){return [...data.agents.map(x=>({...x,kind:'agent'})),...data.goals.map(x=>({...x,kind:'goal'})),...data.skills.map(x=>({...x,kind:'skill'})),...data.tasks.map(x=>({...x,kind:'task'}))]}
function edges(data){const result=[];data.tasks.forEach(t=>{if(t.related_skill_id)result.push([t.id,t.related_skill_id]);if(t.related_goal_id)result.push([t.id,t.related_goal_id])});data.skills.forEach(s=>{JSON.parse(s.dependencies||'[]').forEach(d=>result.push([s.id,d]));if(s.owner_agent_id)result.push([s.id,s.owner_agent_id])});return result}
function draw(){const width=svg.clientWidth||800,height=svg.clientHeight||500;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.innerHTML='';const nodes=nodeData(graphData).filter(n=>active==='all'||typeFor(n)===active);const ids=new Set(nodes.map(n=>n.id));const pos={};nodes.forEach((n,i)=>{const a=(Math.PI*2*i/nodes.length)-Math.PI/2,r=Math.min(width,height)*.3;pos[n.id]={x:width/2+Math.cos(a)*r,y:height/2+Math.sin(a)*r}});edges(graphData).filter(([a,b])=>ids.has(a)&&ids.has(b)).forEach(([a,b])=>{const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('class','edge');line.setAttribute('x1',pos[a].x);line.setAttribute('y1',pos[a].y);line.setAttribute('x2',pos[b].x);line.setAttribute('y2',pos[b].y);svg.append(line)});nodes.forEach(n=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class',`node ${selected?.id===n.id?'selected':''}`);g.setAttribute('transform',`translate(${pos[n.id].x} ${pos[n.id].y})`);const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('r',typeFor(n)==='goal'?22:16);c.setAttribute('fill',color[typeFor(n)]);g.append(c);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('text-anchor','middle');t.setAttribute('y',34);t.textContent=n.name||n.title;g.append(t);g.onclick=()=>{selected=n;showDetail();draw()};svg.append(g)})}
function showDetail(){const e=document.querySelector('#detail');if(!selected){e.innerHTML='<p class="muted">ノードを選択してください。</p>';return}const type=typeFor(selected);e.innerHTML=`<p class="eyebrow">${type.toUpperCase()}</p><h2 class="detail-title">${selected.name||selected.title}</h2><span class="badge">${selected.status||'active'}</span><div class="kv"><b>ID</b><span>${selected.id}</span><b>説明</b><span>${selected.description||'—'}</span><b>信頼度</b><span>${selected.confidence??'—'}</span><b>利用回数</b><span>${selected.usage_count??'—'}</span></div>`}
async function load(){graphData=await fetch('/api/graph').then(r=>r.json());document.querySelector('#skill').innerHTML='<option value="">関連スキル（任意）</option>'+graphData.skills.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');document.querySelector('#activity-list').innerHTML=graphData.events.slice(0,10).map(e=>`<li>${e.event_type}<br><span class="muted">${e.timestamp}</span></li>`).join('')||'<li>まだイベントはありません。</li>';draw()}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{active=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));draw()});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab],.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active')});document.querySelector('#task-form').onsubmit=async e=>{e.preventDefault();const record=await fetch('/api/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:title.value,related_skill_id:skill.value||null})}).then(r=>r.json());document.querySelector('#form-result').textContent=`記録済み: ${record.entity_id}`;e.target.reset();load()};window.onresize=draw;load();
